--What is the total revenue generated by male vs female customers?
select gender, sum(purchase_amount_usd) as revenue
from customer
group by gender

--which customers used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount_usd
from customer
where discount_applied='Yes' 
and purchase_amount_usd >=(select avg(purchase_amount_usd) from customer)

--which are the top 5 products with the highest average review rating?
select item_purchased, round(AVG(review_rating::numeric),2) as average_product_rating
from customer
group by item_purchased 
order by 2 desc
limit 5

--Compare the average purchase amounts between standard and express shipping.
Select shipping_type, ROUND(AVG(purchase_amount_usd),2)
from customer
where shipping_type in ('Express', 'Standard')
group by  shipping_type

--Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,count(customer_id) as total_customers,
ROUND(AVG(purchase_amount_usd),2) as average_spend,
sum(purchase_amount_usd) as total_revenue
from customer
group by subscription_status
order by 2,3,4 desc

--Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by 2 desc
limit 5;

--Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
select 
case when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal' end as customer_segment,
SUM(case when previous_purchases=1 then 1 else 0 end) as New_count,  
SUM(case when previous_purchases>= 2 and previous_purchases<=10 then 1 else 0 end) as Returning_count,
SUM(case when previous_purchases>10 then 1 else 0 end) as Loyal_count  
from customer
group by 1

or 

with seg_cust as ( Select customer_id,
case when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal' end as customer_segment
from customer)

select customer_segment, count(*) as "Number of Customers"
from seg_cust
group by 1

--What are the top 3 most purchased products within each category?
select * from (select category, item_purchased,
row_number() over (partition by category order by count(customer_id) desc) as item_rank,
count(customer_id) as total_orders 
from customer
group by 1,2) a where item_rank<=3

--Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by 1
order by 2 desc

--What is the revenue contribution of each age group?
select age_group, sum(purchase_amount_usd) as total_revenue
from customer
group by 1
order by 1 desc
